export const STYLES = [
  {
    slug: 'monogram-edition',
    name: 'The Monogram Edition',
    shortDesc: 'Your initials, woven into premium ribbed cotton.',
    desc: 'Bold interlocking monogram diamonds set against a rich forest green. Comes as a pair — one patterned, one plain. This is the sock that started it all.',
    price: 28,
    tag: 'Bestseller',
    img: '/socks/monogram.jpg',
    color: '#1a3a2a',
    theme: 'Embroidered initials',
    og: true,
    ogColor: 'Forest Green',
    includes: '2 socks per pair',
  },
  {
    slug: 'navigators-compass',
    name: "The Navigator's Compass",
    shortDesc: 'Anchors, waves, and compass rose on midnight navy.',
    desc: 'Dual-design set — a navy sock bearing a bold compass rose, paired with a cream ankle sock covered in anchor motifs. For the explorer in every room.',
    price: 30,
    tag: null,
    img: '/socks/compass.jpg',
    color: '#0f2d40',
    theme: 'Nautical & ocean',
    og: true,
    ogColor: 'Midnight Navy',
    includes: '2-sock set, dual design',
  },
  {
    slug: 'manifesto-tab',
    name: 'The Manifesto Tab',
    shortDesc: '"never for everyone" — woven into jet black.',
    desc: 'Jet black crew sock. "never for everyone" embroidered in tonal text across the ankle. No loud graphics. No clutter. Just the statement.',
    price: 35,
    tag: 'Signature',
    img: '/socks/manifesto.jpg',
    color: '#111111',
    theme: 'Dark minimal',
    og: true,
    ogColor: 'Jet Black',
    includes: '1 pair',
  },
  {
    slug: 'urban-pulse',
    name: 'Urban Pulse',
    shortDesc: 'City grids and transit maps in soft grey.',
    desc: 'Light heather grey with a subtle city-grid pattern woven throughout. The sock for people who find beauty in infrastructure.',
    price: 30,
    tag: null,
    img: '/socks/urban.jpg',
    color: '#7a7a7a',
    theme: 'City transit',
    og: true,
    ogColor: 'Heather Grey',
    includes: '1 pair',
  },
  {
    slug: 'celestial-strides',
    name: 'Celestial Strides',
    shortDesc: 'Constellations mapped across deep charcoal.',
    desc: 'Dark charcoal base with star constellations and orbital paths mapped across the full sock. Wear the night sky.',
    price: 32,
    tag: 'Fan Favourite',
    img: '/socks/celestial.jpg',
    color: '#1e2030',
    theme: 'Galaxy & stars',
    og: false,
    ogColor: null,
    includes: '1 pair',
  },
  {
    slug: 'botanical-ink',
    name: 'Botanical Ink',
    shortDesc: 'Hand-drawn ferns and botanicals on blush pink.',
    desc: 'Warm rose ankle sock with detailed botanical fern illustrations running the length of the foot. Soft, considered, unmistakably SOXZ.',
    price: 32,
    tag: 'New',
    img: '/socks/botanical.jpg',
    color: '#b5606a',
    theme: 'Botanical garden',
    og: false,
    ogColor: null,
    includes: '1 pair',
  },
  {
    slug: 'celestial-step',
    name: 'Celestial Step',
    shortDesc: 'Moon phases across jet black.',
    desc: 'All-black ankle sock with the full lunar cycle — new moon to full moon — embroidered in muted tones across the top of the foot.',
    price: 32,
    tag: null,
    img: '/socks/moon.jpg',
    color: '#1a1a1a',
    theme: 'Moon phases',
    og: false,
    ogColor: null,
    includes: '1 pair',
  },
  {
    slug: 'retro-cassette',
    name: 'The Retro Cassette',
    shortDesc: 'Bold retro stripe in terracotta, sky, and cream.',
    desc: 'Wide retro stripes in terracotta orange, sky blue, warm cream, and mustard. Decades of style condensed into one pair.',
    price: 30,
    tag: 'Trending',
    img: '/socks/retro.jpg',
    color: '#b5601a',
    theme: 'Retro vibes',
    og: false,
    ogColor: null,
    includes: '1 pair',
  },
  {
    slug: 'the-coordinates',
    name: 'The Coordinates',
    shortDesc: 'Your city. Your GPS coordinates.',
    desc: 'Precise coordinate grid printed across a neutral grey base. Clean, geographic, personal.',
    price: 35,
    tag: null,
    img: '/socks/coordinates.jpg',
    color: '#4a4a4a',
    theme: 'World map',
    og: false,
    ogColor: null,
    includes: '1 pair',
  },
]

export type Style = typeof STYLES[0]

export function getStyle(slug: string): Style | undefined {
  return STYLES.find(s => s.slug === slug)
}

export const OG_STYLES = STYLES.filter(s => s.og)
export const NEW_STYLES = STYLES.filter(s => !s.og)
